language: ruby
rvm:
  - 2.3.0
env:
  - DB=mysql
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database felixfortis_test'
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec