# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8acdd71f5fef1ac2c8c3b57637addafee346cf06866474a2f01ebd4726f58977db59a9bf1116837608a92e8132dc8c514ef30f3cdd47f1337061d59fc2fcc0b

test:
  secret_key_base: 9e4fa0150b7a994cd337cf6e7199aae8fba2620eeae7fadc4e5a49ae94f860b25fb5a20af2da45617f6c801ace8bf0251fd90e368552ab70bd5716101f1ec5d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
