require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GoalsController, type: :controller do
  login_user
  before(:each) {@user = subject.current_user}

  # This should return the minimal set of attributes required to create a valid
  # Goal. As you add validations to Goal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {title: 'bake a pie', due_date: Date.tomorrow, description: "Learn to bake my favourite pie - apple!"}
  }
  let(:invalid_attributes) {
    {title: 'bake a pie', due_date: Date.tomorrow, description: ""}
  }

  describe "GET #index" do
    it "assigns all goals as @goals" do
      goal = @user.goals.create! valid_attributes
      get :index, {}
      expect(assigns(:goals)).to eq([goal])
    end
  end

  describe "GET #show" do
    it "assigns the requested goal as @goal" do
      goal = @user.goals.create! valid_attributes
      get :show, {:id => goal.to_param}
      expect(assigns(:goal)).to eq(goal)
    end
  end

  describe "GET #new" do
    it "assigns a new goal as @goal" do
      get :new, {}
      expect(assigns(:goal)).to be_a_new(Goal)
    end
  end

  describe "GET #edit" do
    it "assigns the requested goal as @goal" do
      goal = @user.goals.create! valid_attributes
      get :edit, {:id => goal.to_param}
      expect(assigns(:goal)).to eq(goal)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Goal" do
        expect {
          post :create, {:goal => valid_attributes}
        }.to change(Goal, :count).by(1)
      end

      it "assigns a newly created goal as @goal" do
        post :create, {:goal => valid_attributes}
        expect(assigns(:goal)).to be_a(Goal)
        expect(assigns(:goal)).to be_persisted
      end

      it "redirects to the created goal" do
        post :create, {:goal => valid_attributes}
        expect(response).to redirect_to(user_goal_path(@user, @user.goals.last))
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved goal as @goal" do
        post :create, {:goal => invalid_attributes}
        expect(assigns(:goal)).to be_a_new(Goal)
      end

      it "re-renders the 'new' template" do
        post :create, {:goal => invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {title: 'bake a HUUUUUGE pie', due_date: 2.days.from_now, description: "Learn to bake my favourite pie - but HUUUUUGE!"}
      }

      it "updates the requested goal" do
        goal = @user.goals.create! valid_attributes
        put :update, {:id => goal.to_param, :goal => new_attributes}
        goal.reload
        expect(goal.attributes[:title]).to eq(new_attributes["title"])
        expect(goal.attributes[:due_date]).to eq(new_attributes["due_date"])
        expect(goal.attributes[:description]).to eq(new_attributes["description"])
      end

      it "assigns the requested goal as @goal" do
        goal = @user.goals.create! valid_attributes
        put :update, {:id => goal.to_param, :goal => valid_attributes}
        expect(assigns(:goal)).to eq(goal)
      end

      it "redirects to the goal" do
        goal = @user.goals.create! valid_attributes
        put :update, {:id => goal.to_param, :goal => valid_attributes}
        expect(response).to redirect_to(user_goal_path(@user, goal))
      end
    end

    context "with invalid params" do
      it "assigns the goal as @goal" do
        goal = @user.goals.create! valid_attributes
        put :update, {:id => goal.to_param, :goal => invalid_attributes}
        expect(assigns(:goal)).to eq(goal)
      end

      it "re-renders the 'edit' template" do
        goal = @user.goals.create! valid_attributes
        put :update, {:id => goal.to_param, :goal => invalid_attributes}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested goal" do
      goal = @user.goals.create! valid_attributes
      expect {
        delete :destroy, {:id => goal.to_param}
      }.to change(Goal, :count).by(-1)
    end

    it "redirects to the goals list" do
      goal = @user.goals.create! valid_attributes
      delete :destroy, {:id => goal.to_param}
      expect(response).to redirect_to(user_goals_url(@user))
    end
  end

end
