require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MilestonesController, type: :controller do

  login_user
  before(:each) {@user = subject.current_user}
  before(:each) {@user.projects.create!(title: 'bake a PIZZA', due_date: Date.tomorrow, description: "Learn to bake my favourite PIZZA - PEPPERONI!")}
  before(:each) {@project = @user.projects.first}

  # This should return the minimal set of attributes required to create a valid
  # Milestone. As you add validations to Milestone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {title: 'bake a pie', due_date: Date.tomorrow, description: "Learn to bake my favourite pie - apple!"}
  }
  let(:invalid_attributes) {
    {title: 'bake a pie', due_date: Date.tomorrow, description: ""}
  }

  describe "GET #index" do
    it "assigns all milestones as @milestones" do
      milestone = @project.milestones.create! valid_attributes
      get :index, {project_id: @project.id}
      expect(assigns(:milestones)).to eq([milestone])
    end
  end

  describe "GET #show" do
    it "assigns the requested milestone as @milestone" do
      milestone = @project.milestones.create! valid_attributes
      get :show, {:id => milestone.to_param, project_id: @project.id}
      expect(assigns(:milestone)).to eq(milestone)
    end
  end

  describe "GET #new" do
    it "assigns a new milestone as @milestone" do
      get :new, {project_id: @project.id}
      expect(assigns(:milestone)).to be_a_new(Milestone)
    end
  end

  describe "GET #edit" do
    it "assigns the requested milestone as @milestone" do
      milestone = @project.milestones.create! valid_attributes
      get :edit, {:id => milestone.to_param, project_id: @project.id}
      expect(assigns(:milestone)).to eq(milestone)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Milestone" do
        expect {
          post :create, {:milestone => valid_attributes, project_id: @project.id}
        }.to change(Milestone, :count).by(1)
      end

      it "assigns a newly created milestone as @milestone" do
        post :create, {:milestone => valid_attributes, project_id: @project.id}
        expect(assigns(:milestone)).to be_a(Milestone)
        expect(assigns(:milestone)).to be_persisted
      end

      it "redirects to the created milestone" do
        post :create, {:milestone => valid_attributes, project_id: @project.id}
        expect(response).to redirect_to(project_milestone_path(@project, @project.milestones.last))
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved milestone as @milestone" do
        post :create, {:milestone => invalid_attributes, project_id: @project.id}
        expect(assigns(:milestone)).to be_a_new(Milestone)
      end

      it "re-renders the 'new' template" do
        post :create, {:milestone => invalid_attributes, project_id: @project.id}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {title: 'bake a CRUMBLE', due_date: 2.days.from_now, description: "Learn to bake my favourite CRUMBLE - RHUBARB!"}
      }

      it "updates the requested milestone" do
        milestone = @project.milestones.create! valid_attributes
        put :update, {:id => milestone.to_param, :milestone => new_attributes, project_id: @project.id}
        milestone.reload
        expect(milestone.attributes[:title]).to eq(new_attributes["title"])
        expect(milestone.attributes[:due_date]).to eq(new_attributes["due_date"])
        expect(milestone.attributes[:description]).to eq(new_attributes["description"])
      end

      it "assigns the requested milestone as @milestone" do
        milestone = @project.milestones.create! valid_attributes
        put :update, {:id => milestone.to_param, :milestone => valid_attributes, project_id: @project.id}
        expect(assigns(:milestone)).to eq(milestone)
      end

      it "redirects to the milestone" do
        milestone = @project.milestones.create! valid_attributes
        put :update, {:id => milestone.to_param, :milestone => valid_attributes, project_id: @project.id}
        expect(response).to redirect_to(project_milestone_url(@project, milestone))
      end
    end

    context "with invalid params" do
      it "assigns the milestone as @milestone" do
        milestone = @project.milestones.create! valid_attributes
        put :update, {:id => milestone.to_param, :milestone => invalid_attributes, project_id: @project.id}
        expect(assigns(:milestone)).to eq(milestone)
      end

      it "re-renders the 'edit' template" do
        milestone = @project.milestones.create! valid_attributes
        put :update, {:id => milestone.to_param, :milestone => invalid_attributes, project_id: @project.id}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested milestone" do
      milestone = @project.milestones.create! valid_attributes
      expect {
        delete :destroy, {:id => milestone.to_param, project_id: @project.id}
      }.to change(Milestone, :count).by(-1)
    end

    it "redirects to the milestones list" do
      milestone = @project.milestones.create! valid_attributes
      delete :destroy, {:id => milestone.to_param, project_id: @project.id}
      expect(response).to redirect_to(project_milestones_url(@project))
    end
  end

end
